"""
Nexus Monitor Agent - Background System Health Monitoring
Proactively watches CPU, Memory, Disk, and system processes
"""

import asyncio
from typing import Dict, Any, Callable, Optional, List
from dataclasses import dataclass
from datetime import datetime

try:
    import psutil
    PSUTIL_AVAILABLE = True
except ImportError:
    PSUTIL_AVAILABLE = False
    psutil = None


@dataclass
class SystemAlert:
    """Alert generated by the monitor"""
    alert_type: str  # cpu, memory, disk, process
    severity: str    # info, warning, critical
    message: str
    value: float
    threshold: float
    timestamp: str


@dataclass
class SystemHealth:
    """Current system health snapshot"""
    cpu_percent: float
    memory_percent: float
    disk_percent: float
    top_processes: List[Dict[str, Any]]
    timestamp: str


class MonitorAgent:
    """
    Monitor Agent - Background System Health Watcher
    
    Runs as an async background task, periodically checking:
    - CPU usage
    - Memory usage
    - Disk usage
    - High-resource processes (e.g., Docker, inference)
    
    Emits alerts when thresholds are exceeded.
    """
    
    # Default thresholds
    DEFAULT_THRESHOLDS = {
        "cpu_warning": 70.0,
        "cpu_critical": 90.0,
        "memory_warning": 75.0,
        "memory_critical": 90.0,
        "disk_warning": 80.0,
        "disk_critical": 95.0,
    }
    
    # Processes to watch for high usage
    WATCHED_PROCESSES = ["docker", "ollama", "python", "node", "code"]
    
    def __init__(
        self,
        alert_callback: Optional[Callable[[SystemAlert], None]] = None,
        thresholds: Optional[Dict[str, float]] = None,
        check_interval: int = 60
    ):
        self.alert_callback = alert_callback
        self.thresholds = {**self.DEFAULT_THRESHOLDS, **(thresholds or {})}
        self.check_interval = check_interval
        self._running = False
        self._task: Optional[asyncio.Task] = None
        self._last_health: Optional[SystemHealth] = None
    
    @property
    def is_available(self) -> bool:
        return PSUTIL_AVAILABLE
    
    @property
    def is_running(self) -> bool:
        return self._running
    
    async def start_monitoring(self):
        """Start the background monitoring loop"""
        if not PSUTIL_AVAILABLE:
            return
        
        self._running = True
        self._task = asyncio.create_task(self._monitor_loop())
    
    async def stop_monitoring(self):
        """Stop the background monitoring"""
        self._running = False
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
    
    async def _monitor_loop(self):
        """Main monitoring loop"""
        while self._running:
            try:
                await self.check_system_health()
                await asyncio.sleep(self.check_interval)
            except asyncio.CancelledError:
                break
            except Exception:
                await asyncio.sleep(self.check_interval)
    
    async def check_system_health(self) -> SystemHealth:
        """Perform a full system health check"""
        if not PSUTIL_AVAILABLE:
            return None
        
        cpu = await self._check_cpu()
        memory = await self._check_memory()
        disk = await self._check_disk()
        processes = await self._check_processes()
        
        health = SystemHealth(
            cpu_percent=cpu,
            memory_percent=memory,
            disk_percent=disk,
            top_processes=processes,
            timestamp=datetime.utcnow().isoformat()
        )
        self._last_health = health
        return health
    
    async def _check_cpu(self) -> float:
        """Check CPU usage and emit alerts"""
        # Use non-blocking call
        cpu = await asyncio.get_event_loop().run_in_executor(
            None, lambda: psutil.cpu_percent(interval=1)
        )
        
        if cpu >= self.thresholds["cpu_critical"]:
            self._emit_alert("cpu", "critical", f"CPU usage critical: {cpu:.1f}%", cpu, self.thresholds["cpu_critical"])
        elif cpu >= self.thresholds["cpu_warning"]:
            self._emit_alert("cpu", "warning", f"CPU usage high: {cpu:.1f}%", cpu, self.thresholds["cpu_warning"])
        
        return cpu
    
    async def _check_memory(self) -> float:
        """Check memory usage and emit alerts"""
        mem = psutil.virtual_memory()
        percent = mem.percent
        
        if percent >= self.thresholds["memory_critical"]:
            self._emit_alert("memory", "critical", f"Memory usage critical: {percent:.1f}%", percent, self.thresholds["memory_critical"])
        elif percent >= self.thresholds["memory_warning"]:
            self._emit_alert("memory", "warning", f"Memory usage high: {percent:.1f}%", percent, self.thresholds["memory_warning"])
        
        return percent
    
    async def _check_disk(self) -> float:
        """Check disk usage and emit alerts"""
        # Check root partition
        disk = psutil.disk_usage("/")
        percent = disk.percent
        
        if percent >= self.thresholds["disk_critical"]:
            self._emit_alert("disk", "critical", f"Disk usage critical: {percent:.1f}%", percent, self.thresholds["disk_critical"])
        elif percent >= self.thresholds["disk_warning"]:
            self._emit_alert("disk", "warning", f"Disk usage high: {percent:.1f}%", percent, self.thresholds["disk_warning"])
        
        return percent
    
    async def _check_processes(self) -> List[Dict[str, Any]]:
        """Check for high-resource processes"""
        top_procs = []
        
        try:
            for proc in psutil.process_iter(["pid", "name", "cpu_percent", "memory_percent"]):
                try:
                    info = proc.info
                    name = info.get("name", "").lower()
                    
                    # Check if it's a watched process
                    for watched in self.WATCHED_PROCESSES:
                        if watched in name:
                            cpu = info.get("cpu_percent", 0)
                            mem = info.get("memory_percent", 0)
                            
                            if cpu > 50 or mem > 10:
                                top_procs.append({
                                    "pid": info.get("pid"),
                                    "name": info.get("name"),
                                    "cpu_percent": cpu,
                                    "memory_percent": mem
                                })
                                
                                if cpu > 80:
                                    self._emit_alert(
                                        "process", "warning",
                                        f"High CPU in {info.get('name')}: {cpu:.1f}%",
                                        cpu, 80.0
                                    )
                            break
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    continue
        except Exception:
            pass
        
        return sorted(top_procs, key=lambda x: x.get("cpu_percent", 0), reverse=True)[:5]
    
    def _emit_alert(self, alert_type: str, severity: str, message: str, value: float, threshold: float):
        """Emit an alert through the callback"""
        alert = SystemAlert(
            alert_type=alert_type,
            severity=severity,
            message=message,
            value=value,
            threshold=threshold,
            timestamp=datetime.utcnow().isoformat()
        )
        
        if self.alert_callback:
            self.alert_callback(alert)
    
    def get_last_health(self) -> Optional[SystemHealth]:
        """Get the most recent health snapshot"""
        return self._last_health
    
    def update_thresholds(self, new_thresholds: Dict[str, float]):
        """Update monitoring thresholds"""
        self.thresholds.update(new_thresholds)
